# Generated by Django 3.2.9 on 2022-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='x',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.AlterField(
            model_name='examdutyallottment',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
