# Generated by Django 3.2.9 on 2022-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20221117_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('bennett_email', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
